In [1]:
import numpy as np
import pandas as pd

car_dim = pd.read_csv('Car_Dimensions.csv')
car_dim.head(10)

   CarID  Dimensions.Height  Dimensions.Length  Dimensions.Width
0      1                140                143               202
1      2                140                143               202
2      3                140                143               202
3      4                140                143               202
4      5                140                143               202
5      6                 91                 17                62
6      7                 91                 17                62
7      8                201                221               191
8      9                201                221               191
9     10                147                 96                34

In [2]:
eng_fuel = pd.read_csv('Engine_Fuel.csv')
eng_fuel.head()

,CarID,Engine Information.Driveline,Engine Information.Engine Type,Engine Information.Hybrid,Engine Information.Number of Forward Gears,Engine Information.Transmission,Fuel Information.City mpg,Fuel Information.Fuel Type,Fuel Information.Highway mpg,Identification.Classification
0,1,All-wheel drive,Audi 3.2L 6 cylinder 250hp 236ft-lbs,True,6,6 Speed Automatic Select Shift,18,Gasoline,25,Automatic transmission
1,2,Front-wheel drive,Audi 2.0L 4 cylinder 200 hp 207 ft-lbs Turbo,True,6,6 Speed Automatic Select Shift,22,Gasoline,28,Automatic transmission
2,3,Front-wheel drive,Audi 2.0L 4 cylinder 200 hp 207 ft-lbs Turbo,True,6,6 Speed Manual,21,Gasoline,30,Manual transmission
3,4,All-wheel drive,Audi 2.0L 4 cylinder 200 hp 207 ft-lbs Turbo,True,6,6 Speed Automatic Select Shift,21,Gasoline,28,Automatic transmission
4,5,All-wheel drive,Audi 2.0L 4 cylinder 200 hp 207 ft-lbs Turbo,True,6,6 Speed Automatic Select Shift,21,Gasoline,28,Automatic transmission

In [3]:
model_name = pd.read_csv('CarModelNo_Name.csv')
model_name.head()

,CarID,Identification.Classification,Identification.ID,Identification.Make
0,1,Automatic transmission,2009 Audi A3 3.2,Audi
1,2,Automatic transmission,2009 Audi A3 2.0 T AT,Audi
2,3,Manual transmission,2009 Audi A3 2.0 T,Audi
3,4,Automatic transmission,2009 Audi A3 2.0 T Quattro,Audi
4,5,Automatic transmission,2009 Audi A3 2.0 T Quattro,Audi

In [4]:
eng_dim = pd.merge(eng_fuel, model_name, on='CarID')

In [5]:
eng_dim.head(4)

,CarID,Engine Information.Driveline,Engine Information.Engine Type,Engine Information.Hybrid,Engine Information.Number of Forward Gears,Engine Information.Transmission,Fuel Information.City mpg,Fuel Information.Fuel Type,Fuel Information.Highway mpg,Identification.Classification_x,Identification.Classification_y,Identification.ID,Identification.Make
0,1,All-wheel drive,Audi 3.2L 6 cylinder 250hp 236ft-lbs,True,6,6 Speed Automatic Select Shift,18,Gasoline,25,Automatic transmission,Automatic transmission,2009 Audi A3 3.2,Audi
1,2,Front-wheel drive,Audi 2.0L 4 cylinder 200 hp 207 ft-lbs Turbo,True,6,6 Speed Automatic Select Shift,22,Gasoline,28,Automatic transmission,Automatic transmission,2009 Audi A3 2.0 T AT,Audi
2,3,Front-wheel drive,Audi 2.0L 4 cylinder 200 hp 207 ft-lbs Turbo,True,6,6 Speed Manual,21,Gasoline,30,Manual transmission,Manual transmission,2009 Audi A3 2.0 T,Audi
3,4,All-wheel drive,Audi 2.0L 4 cylinder 200 hp 207 ft-lbs Turbo,True,6,6 Speed Automatic Select Shift,21,Gasoline,28,Automatic transmission,Automatic transmission,2009 Audi A3 2.0 T Quattro,Audi

In [6]:
eng_dim.groupby('Identification.ID')['Fuel Information.City mpg'].head()

0       18
1       22
2       21
3       21
4       21
        ..
5071    18
5072    12
5073    12
5074    17
5075    17
Name: Fuel Information.City mpg, Length: 5076, dtype: int64